# Generated by Django 5.1.6 on 2025-02-23 11:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='البريد الإلكتروني'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='الحساب مفعل؟'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='⚠️ رقم الجوال يجب أن يتكون من 10 أرقام فقط ويبدأ بـ 05.', regex='^05[0-9]{8}$')], verbose_name='رقم الجوال'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='resume',
            field=models.FileField(upload_to='resumes/', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='السيرة الذاتية'),
        ),
    ]
