# Generated by Django 5.1.6 on 2025-02-23 12:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_email_alter_customuser_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='⚠️ رقم الجوال يجب أن يتكون من 10 أرقام فقط ويبدأ بـ 05.', regex='^05[0-9]{8}$')], verbose_name='رقم الجوال'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resumes/', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='السيرة الذاتية'),
        ),
    ]
