# Generated by Django 5.1.6 on 2025-02-23 12:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='⚠️ رقم الجوال يجب أن يبدأ بـ 05 ويتكون من 10 أرقام.', regex='^05[0-9]{8}$')]),
        ),
    ]
