# Generated by Django 5.1.6 on 2025-02-23 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_accountprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='activation_token',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='رمز التفعيل'),
        ),
    ]
