# Generated by Django 5.1.6 on 2025-03-06 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_customuser_activation_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='token_used',
            field=models.BooleanField(default=False, verbose_name='تم استخدام رمز التفعيل؟'),
        ),
    ]
